// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: athletes.proto

package athletes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AthleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName      string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName       string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	SubscriptionId int32  `protobuf:"varint,3,opt,name=subscriptionId,proto3" json:"subscriptionId,omitempty"`
	GroupId        int32  `protobuf:"varint,4,opt,name=groupId,proto3" json:"groupId,omitempty"`
	DaysLeft       int32  `protobuf:"varint,5,opt,name=daysLeft,proto3" json:"daysLeft,omitempty"`
	DateLast       string `protobuf:"bytes,6,opt,name=dateLast,proto3" json:"dateLast,omitempty"`
	Status         string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Id             int32  `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AthleteRequest) Reset() {
	*x = AthleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_athletes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AthleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AthleteRequest) ProtoMessage() {}

func (x *AthleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athletes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AthleteRequest.ProtoReflect.Descriptor instead.
func (*AthleteRequest) Descriptor() ([]byte, []int) {
	return file_athletes_proto_rawDescGZIP(), []int{0}
}

func (x *AthleteRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AthleteRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AthleteRequest) GetSubscriptionId() int32 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

func (x *AthleteRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *AthleteRequest) GetDaysLeft() int32 {
	if x != nil {
		return x.DaysLeft
	}
	return 0
}

func (x *AthleteRequest) GetDateLast() string {
	if x != nil {
		return x.DateLast
	}
	return ""
}

func (x *AthleteRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AthleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AthleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AthleteResponse) Reset() {
	*x = AthleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_athletes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AthleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AthleteResponse) ProtoMessage() {}

func (x *AthleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_athletes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AthleteResponse.ProtoReflect.Descriptor instead.
func (*AthleteResponse) Descriptor() ([]byte, []int) {
	return file_athletes_proto_rawDescGZIP(), []int{1}
}

func (x *AthleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAthletesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int32 `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
}

func (x *GetAthletesRequest) Reset() {
	*x = GetAthletesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_athletes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAthletesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAthletesRequest) ProtoMessage() {}

func (x *GetAthletesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athletes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAthletesRequest.ProtoReflect.Descriptor instead.
func (*GetAthletesRequest) Descriptor() ([]byte, []int) {
	return file_athletes_proto_rawDescGZIP(), []int{2}
}

func (x *GetAthletesRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetAthletesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Athlete *AthleteRequest `protobuf:"bytes,1,opt,name=athlete,proto3" json:"athlete,omitempty"`
}

func (x *GetAthletesResponse) Reset() {
	*x = GetAthletesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_athletes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAthletesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAthletesResponse) ProtoMessage() {}

func (x *GetAthletesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_athletes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAthletesResponse.ProtoReflect.Descriptor instead.
func (*GetAthletesResponse) Descriptor() ([]byte, []int) {
	return file_athletes_proto_rawDescGZIP(), []int{3}
}

func (x *GetAthletesResponse) GetAthlete() *AthleteRequest {
	if x != nil {
		return x.Athlete
	}
	return nil
}

type DeleteAthletesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []int32 `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteAthletesRequest) Reset() {
	*x = DeleteAthletesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_athletes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAthletesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAthletesRequest) ProtoMessage() {}

func (x *DeleteAthletesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athletes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAthletesRequest.ProtoReflect.Descriptor instead.
func (*DeleteAthletesRequest) Descriptor() ([]byte, []int) {
	return file_athletes_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAthletesRequest) GetId() []int32 {
	if x != nil {
		return x.Id
	}
	return nil
}

type EditAthletesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Athlete []*AthleteRequest `protobuf:"bytes,1,rep,name=athlete,proto3" json:"athlete,omitempty"`
}

func (x *EditAthletesRequest) Reset() {
	*x = EditAthletesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_athletes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditAthletesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAthletesRequest) ProtoMessage() {}

func (x *EditAthletesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athletes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAthletesRequest.ProtoReflect.Descriptor instead.
func (*EditAthletesRequest) Descriptor() ([]byte, []int) {
	return file_athletes_proto_rawDescGZIP(), []int{5}
}

func (x *EditAthletesRequest) GetAthlete() []*AthleteRequest {
	if x != nil {
		return x.Athlete
	}
	return nil
}

type TrainingData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DaysLeft int32  `protobuf:"varint,2,opt,name=daysLeft,proto3" json:"daysLeft,omitempty"`
	DateLast string `protobuf:"bytes,3,opt,name=dateLast,proto3" json:"dateLast,omitempty"`
}

func (x *TrainingData) Reset() {
	*x = TrainingData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_athletes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingData) ProtoMessage() {}

func (x *TrainingData) ProtoReflect() protoreflect.Message {
	mi := &file_athletes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingData.ProtoReflect.Descriptor instead.
func (*TrainingData) Descriptor() ([]byte, []int) {
	return file_athletes_proto_rawDescGZIP(), []int{6}
}

func (x *TrainingData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TrainingData) GetDaysLeft() int32 {
	if x != nil {
		return x.DaysLeft
	}
	return 0
}

func (x *TrainingData) GetDateLast() string {
	if x != nil {
		return x.DateLast
	}
	return ""
}

type AddTrainingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Training []*TrainingData `protobuf:"bytes,1,rep,name=training,proto3" json:"training,omitempty"`
}

func (x *AddTrainingRequest) Reset() {
	*x = AddTrainingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_athletes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTrainingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrainingRequest) ProtoMessage() {}

func (x *AddTrainingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athletes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrainingRequest.ProtoReflect.Descriptor instead.
func (*AddTrainingRequest) Descriptor() ([]byte, []int) {
	return file_athletes_proto_rawDescGZIP(), []int{7}
}

func (x *AddTrainingRequest) GetTraining() []*TrainingData {
	if x != nil {
		return x.Training
	}
	return nil
}

type MinusTrainingOfSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubcriptionId int32 `protobuf:"varint,1,opt,name=subcriptionId,proto3" json:"subcriptionId,omitempty"`
}

func (x *MinusTrainingOfSubscriptionRequest) Reset() {
	*x = MinusTrainingOfSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_athletes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinusTrainingOfSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinusTrainingOfSubscriptionRequest) ProtoMessage() {}

func (x *MinusTrainingOfSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athletes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinusTrainingOfSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*MinusTrainingOfSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_athletes_proto_rawDescGZIP(), []int{8}
}

func (x *MinusTrainingOfSubscriptionRequest) GetSubcriptionId() int32 {
	if x != nil {
		return x.SubcriptionId
	}
	return 0
}

var File_athletes_proto protoreflect.FileDescriptor

var file_athletes_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x22, 0xec, 0x01, 0x0a, 0x0e, 0x41,
	0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x79,
	0x73, 0x4c, 0x65, 0x66, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x61, 0x79,
	0x73, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x73,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x0f, 0x41, 0x74, 0x68,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x74, 0x68,
	0x6c, 0x65, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x74, 0x68,
	0x6c, 0x65, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a,
	0x07, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x2e, 0x41, 0x74, 0x68, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74,
	0x65, 0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x68, 0x6c, 0x65,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x13, 0x45, 0x64,
	0x69, 0x74, 0x41, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x32, 0x0a, 0x07, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x2e, 0x41, 0x74,
	0x68, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x61, 0x74,
	0x68, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x56, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e,
	0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x79, 0x73, 0x4c, 0x65, 0x66,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x61, 0x79, 0x73, 0x4c, 0x65, 0x66,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x73, 0x74, 0x22, 0x48, 0x0a,
	0x12, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x73,
	0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x4a, 0x0a, 0x22, 0x4d, 0x69, 0x6e, 0x75, 0x73,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x66, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x0d, 0x73, 0x75, 0x62, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x75, 0x62, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x32, 0xf2, 0x03, 0x0a, 0x0e, 0x41, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74,
	0x65, 0x73, 0x2e, 0x41, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x2e, 0x41, 0x74, 0x68,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x12, 0x1c, 0x2e,
	0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x74, 0x68, 0x6c,
	0x65, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x74,
	0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x2e, 0x41, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4e, 0x0a, 0x0e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x61, 0x74,
	0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x68,
	0x6c, 0x65, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61,
	0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x2e, 0x41, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0b, 0x45, 0x64, 0x69,
	0x74, 0x41, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x61, 0x74, 0x68, 0x6c, 0x65,
	0x74, 0x65, 0x73, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x41, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74,
	0x65, 0x73, 0x2e, 0x41, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x12, 0x1c, 0x2e, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x2e, 0x41,
	0x64, 0x64, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x2e, 0x41, 0x74, 0x68,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68,
	0x0a, 0x1b, 0x4d, 0x69, 0x6e, 0x75, 0x73, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x4f,
	0x66, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x2e,
	0x61, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x2e, 0x4d, 0x69, 0x6e, 0x75, 0x73, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x66, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x74,
	0x68, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x2e, 0x41, 0x74, 0x68, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x61, 0x74, 0x68, 0x6c,
	0x65, 0x74, 0x65, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_athletes_proto_rawDescOnce sync.Once
	file_athletes_proto_rawDescData = file_athletes_proto_rawDesc
)

func file_athletes_proto_rawDescGZIP() []byte {
	file_athletes_proto_rawDescOnce.Do(func() {
		file_athletes_proto_rawDescData = protoimpl.X.CompressGZIP(file_athletes_proto_rawDescData)
	})
	return file_athletes_proto_rawDescData
}

var file_athletes_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_athletes_proto_goTypes = []interface{}{
	(*AthleteRequest)(nil),                     // 0: athletes.AthleteRequest
	(*AthleteResponse)(nil),                    // 1: athletes.AthleteResponse
	(*GetAthletesRequest)(nil),                 // 2: athletes.GetAthletesRequest
	(*GetAthletesResponse)(nil),                // 3: athletes.GetAthletesResponse
	(*DeleteAthletesRequest)(nil),              // 4: athletes.DeleteAthletesRequest
	(*EditAthletesRequest)(nil),                // 5: athletes.EditAthletesRequest
	(*TrainingData)(nil),                       // 6: athletes.TrainingData
	(*AddTrainingRequest)(nil),                 // 7: athletes.AddTrainingRequest
	(*MinusTrainingOfSubscriptionRequest)(nil), // 8: athletes.MinusTrainingOfSubscriptionRequest
}
var file_athletes_proto_depIdxs = []int32{
	0, // 0: athletes.GetAthletesResponse.athlete:type_name -> athletes.AthleteRequest
	0, // 1: athletes.EditAthletesRequest.athlete:type_name -> athletes.AthleteRequest
	6, // 2: athletes.AddTrainingRequest.training:type_name -> athletes.TrainingData
	0, // 3: athletes.AthleteService.CreateAthlete:input_type -> athletes.AthleteRequest
	2, // 4: athletes.AthleteService.GetAthletes:input_type -> athletes.GetAthletesRequest
	4, // 5: athletes.AthleteService.DeleteAthletes:input_type -> athletes.DeleteAthletesRequest
	5, // 6: athletes.AthleteService.EditAthlete:input_type -> athletes.EditAthletesRequest
	7, // 7: athletes.AthleteService.AddTraining:input_type -> athletes.AddTrainingRequest
	8, // 8: athletes.AthleteService.MinusTrainingOfSubscription:input_type -> athletes.MinusTrainingOfSubscriptionRequest
	1, // 9: athletes.AthleteService.CreateAthlete:output_type -> athletes.AthleteResponse
	0, // 10: athletes.AthleteService.GetAthletes:output_type -> athletes.AthleteRequest
	1, // 11: athletes.AthleteService.DeleteAthletes:output_type -> athletes.AthleteResponse
	1, // 12: athletes.AthleteService.EditAthlete:output_type -> athletes.AthleteResponse
	1, // 13: athletes.AthleteService.AddTraining:output_type -> athletes.AthleteResponse
	1, // 14: athletes.AthleteService.MinusTrainingOfSubscription:output_type -> athletes.AthleteResponse
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_athletes_proto_init() }
func file_athletes_proto_init() {
	if File_athletes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_athletes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AthleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_athletes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AthleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_athletes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAthletesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_athletes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAthletesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_athletes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAthletesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_athletes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditAthletesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_athletes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainingData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_athletes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTrainingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_athletes_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinusTrainingOfSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_athletes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_athletes_proto_goTypes,
		DependencyIndexes: file_athletes_proto_depIdxs,
		MessageInfos:      file_athletes_proto_msgTypes,
	}.Build()
	File_athletes_proto = out.File
	file_athletes_proto_rawDesc = nil
	file_athletes_proto_goTypes = nil
	file_athletes_proto_depIdxs = nil
}
