// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: subscription.proto

package subscription

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TypeSubscriptionService_CreateSubscription_FullMethodName          = "/subscription.TypeSubscriptionService/CreateSubscription"
	TypeSubscriptionService_GetSubscriptionDaysOfWeek_FullMethodName   = "/subscription.TypeSubscriptionService/GetSubscriptionDaysOfWeek"
	TypeSubscriptionService_SubscriptionIsAutomatically_FullMethodName = "/subscription.TypeSubscriptionService/SubscriptionIsAutomatically"
)

// TypeSubscriptionServiceClient is the client API for TypeSubscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TypeSubscriptionServiceClient interface {
	CreateSubscription(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	GetSubscriptionDaysOfWeek(ctx context.Context, in *SubscriptionDataRequest, opts ...grpc.CallOption) (*SubscriptionDataResponse, error)
	SubscriptionIsAutomatically(ctx context.Context, in *SubscriptionDataRequest, opts ...grpc.CallOption) (*SubscriptionIsAutomaticallyResponse, error)
}

type typeSubscriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTypeSubscriptionServiceClient(cc grpc.ClientConnInterface) TypeSubscriptionServiceClient {
	return &typeSubscriptionServiceClient{cc}
}

func (c *typeSubscriptionServiceClient) CreateSubscription(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, TypeSubscriptionService_CreateSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typeSubscriptionServiceClient) GetSubscriptionDaysOfWeek(ctx context.Context, in *SubscriptionDataRequest, opts ...grpc.CallOption) (*SubscriptionDataResponse, error) {
	out := new(SubscriptionDataResponse)
	err := c.cc.Invoke(ctx, TypeSubscriptionService_GetSubscriptionDaysOfWeek_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typeSubscriptionServiceClient) SubscriptionIsAutomatically(ctx context.Context, in *SubscriptionDataRequest, opts ...grpc.CallOption) (*SubscriptionIsAutomaticallyResponse, error) {
	out := new(SubscriptionIsAutomaticallyResponse)
	err := c.cc.Invoke(ctx, TypeSubscriptionService_SubscriptionIsAutomatically_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TypeSubscriptionServiceServer is the server API for TypeSubscriptionService service.
// All implementations must embed UnimplementedTypeSubscriptionServiceServer
// for forward compatibility
type TypeSubscriptionServiceServer interface {
	CreateSubscription(context.Context, *SubscriptionRequest) (*SubscriptionResponse, error)
	GetSubscriptionDaysOfWeek(context.Context, *SubscriptionDataRequest) (*SubscriptionDataResponse, error)
	SubscriptionIsAutomatically(context.Context, *SubscriptionDataRequest) (*SubscriptionIsAutomaticallyResponse, error)
	mustEmbedUnimplementedTypeSubscriptionServiceServer()
}

// UnimplementedTypeSubscriptionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTypeSubscriptionServiceServer struct {
}

func (UnimplementedTypeSubscriptionServiceServer) CreateSubscription(context.Context, *SubscriptionRequest) (*SubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (UnimplementedTypeSubscriptionServiceServer) GetSubscriptionDaysOfWeek(context.Context, *SubscriptionDataRequest) (*SubscriptionDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriptionDaysOfWeek not implemented")
}
func (UnimplementedTypeSubscriptionServiceServer) SubscriptionIsAutomatically(context.Context, *SubscriptionDataRequest) (*SubscriptionIsAutomaticallyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscriptionIsAutomatically not implemented")
}
func (UnimplementedTypeSubscriptionServiceServer) mustEmbedUnimplementedTypeSubscriptionServiceServer() {
}

// UnsafeTypeSubscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TypeSubscriptionServiceServer will
// result in compilation errors.
type UnsafeTypeSubscriptionServiceServer interface {
	mustEmbedUnimplementedTypeSubscriptionServiceServer()
}

func RegisterTypeSubscriptionServiceServer(s grpc.ServiceRegistrar, srv TypeSubscriptionServiceServer) {
	s.RegisterService(&TypeSubscriptionService_ServiceDesc, srv)
}

func _TypeSubscriptionService_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeSubscriptionServiceServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypeSubscriptionService_CreateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeSubscriptionServiceServer).CreateSubscription(ctx, req.(*SubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypeSubscriptionService_GetSubscriptionDaysOfWeek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeSubscriptionServiceServer).GetSubscriptionDaysOfWeek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypeSubscriptionService_GetSubscriptionDaysOfWeek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeSubscriptionServiceServer).GetSubscriptionDaysOfWeek(ctx, req.(*SubscriptionDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypeSubscriptionService_SubscriptionIsAutomatically_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeSubscriptionServiceServer).SubscriptionIsAutomatically(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypeSubscriptionService_SubscriptionIsAutomatically_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeSubscriptionServiceServer).SubscriptionIsAutomatically(ctx, req.(*SubscriptionDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TypeSubscriptionService_ServiceDesc is the grpc.ServiceDesc for TypeSubscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TypeSubscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subscription.TypeSubscriptionService",
	HandlerType: (*TypeSubscriptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSubscription",
			Handler:    _TypeSubscriptionService_CreateSubscription_Handler,
		},
		{
			MethodName: "GetSubscriptionDaysOfWeek",
			Handler:    _TypeSubscriptionService_GetSubscriptionDaysOfWeek_Handler,
		},
		{
			MethodName: "SubscriptionIsAutomatically",
			Handler:    _TypeSubscriptionService_SubscriptionIsAutomatically_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subscription.proto",
}
